import Koneksi.Connect;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Koneksi.database;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user
 */
public class Data_Transaksi extends javax.swing.JFrame {
    DefaultTableModel model=new DefaultTableModel();
    long sumtotal=0;
    long sumtotal2=0;
    /**
     * 
     */
    
    public Data_Transaksi() throws SQLException {
        initComponents();
        database.koneksi();
        tglskrg();
        buatnomer();
        aturtable();
        xkode_barang.requestFocus();
    }
    private void tglskrg(){
        Date skrg=new Date();
        SimpleDateFormat format=new SimpleDateFormat("yyyy-M-dd");
        String tanggal = format.format(skrg);
        txt_tanggal.setText(format.format(skrg));
    }
    private void totalharga(){
        int jumlah = model.getRowCount();
        int totalBiaya = 0;
        int total_harga;
        for(int i=0; i<jumlah; i++) {
            total_harga = Integer.valueOf(model.getValueAt(1, 4).toString());
            totalBiaya += total_harga ;
        }
        xtotal.setText(String.valueOf(totalBiaya));
    }
    private void buatnomer(){
        try {
            ResultSet rs = database.AmbilData("Select no_transaksi as auto from tbl_transaksi ORDER by no_transaksi desc");
            if(rs.next()){
                int no_u = Integer.parseInt(rs.getString("auto")) + 1;
                xno_transaksi.setText(Integer.toString(no_u));
            }else{
                int no_t = 1;
                xno_transaksi.setText(Integer.toString(no_t));
            }
                rs.close();
        } catch (Exception e) {
        }
    }
    private void aturtable(){
        DefaultTableModel tbl = new DefaultTableModel();
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga Barang");
        model.addColumn("Jumlah Barang");
        model.addColumn("Jumlah Harga");
        model.addColumn("Id Admin");
        jTable1.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_tanggal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbutton1 = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        xkembali = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        xbayar = new javax.swing.JTextField();
        xtotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        xstock = new javax.swing.JPanel();
        xkode_barang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        xjml = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_stok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        xnama_barang = new javax.swing.JTextField();
        xharga_jual = new javax.swing.JTextField();
        xno_transaksi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        xjml_harga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_idadmin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));

        jLabel8.setText("Tanggal");

        txt_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tanggalActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbutton1.setText("HAPUS");
        jbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton1ActionPerformed(evt);
            }
        });

        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        btn_cetak.setText("CETAK");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        xkembali.setEditable(false);
        xkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xkembaliActionPerformed(evt);
            }
        });

        jLabel13.setText("TOTAL");

        jLabel10.setText("BAYAR");

        xbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xbayarActionPerformed(evt);
            }
        });

        xtotal.setEditable(false);
        xtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtotalActionPerformed(evt);
            }
        });

        jLabel11.setText("KEMBALI");

        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbatal.setText("BATAL");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(xtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(xkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnbatal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel11)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnkeluar)
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsimpan)
                    .addComponent(btnbatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnkeluar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        xstock.setBackground(new java.awt.Color(204, 204, 255));

        xkode_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xkode_barangActionPerformed(evt);
            }
        });

        jLabel3.setText("KODE BARANG");

        jLabel4.setText("NAMA BARANG");

        xjml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xjmlActionPerformed(evt);
            }
        });

        jLabel7.setText("QTY");

        jLabel6.setText("HARGA");

        txt_stok.setEditable(false);
        txt_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stokActionPerformed(evt);
            }
        });

        jLabel5.setText("STOK");

        xnama_barang.setEditable(false);
        xnama_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xnama_barangActionPerformed(evt);
            }
        });

        xharga_jual.setEditable(false);
        xharga_jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xharga_jualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout xstockLayout = new javax.swing.GroupLayout(xstock);
        xstock.setLayout(xstockLayout);
        xstockLayout.setHorizontalGroup(
            xstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xstockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xkode_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(xstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(xnama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(xstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(xstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(xharga_jual, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(xstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(xjml, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        xstockLayout.setVerticalGroup(
            xstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xstockLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(xstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(xstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xkode_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xjml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xnama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xharga_jual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLabel1.setText("No Transaksi");

        xjml_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xjml_hargaActionPerformed(evt);
            }
        });

        jLabel9.setText("JUMLAH HARGA");

        jLabel2.setText("ID Admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cetak))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(xjml_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39))))
                    .addComponent(xstock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xno_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_idadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbutton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xjml_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambah)
                            .addComponent(btn_cetak))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xno_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txt_idadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbutton1))
                        .addGap(18, 18, 18)
                        .addComponent(xstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xjmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xjmlActionPerformed
        // TODO add your handling code here:
        int al,a2,tot, stock_barang = Integer.parseInt(txt_stok.getText()), jmlbarang = Integer.parseInt(xjml.getText());
        if (stock_barang>=jmlbarang) {
            al = Integer.parseInt(xharga_jual.getText());
            a2 = Integer.parseInt(xjml.getText());
            tot = al*a2;
            xjml_harga.setText(String.valueOf(tot));
            tambah.requestFocus();
        } else {
            JOptionPane.showConfirmDialog(null, "Maaf, \nstock sudah mencapai stock minimal");
        }    
    }//GEN-LAST:event_xjmlActionPerformed

    private void xkode_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xkode_barangActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = database.AmbilData("SELECT * FROM tbl_barang WHERE kd_barang='"+xkode_barang.getText()+"'");
            if (rs.next()) {
                xkode_barang.setText(rs.getString("kd_barang"));
                xnama_barang.setText(rs.getString("nma_barang"));
                txt_stok.setText(rs.getString("stok"));
                xharga_jual.setText(rs.getString("hrga_barang"));
                xjml.requestFocus();
            }else{
                JOptionPane.showMessageDialog(null, "Data belum terdaftar");
                xkode_barang.selectAll();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_xkode_barangActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        try {
            int n = JOptionPane.showConfirmDialog(this, "Tambah Item Lagi?", "RPL Message",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null);
            if (n== JOptionPane.YES_NO_OPTION){
                long qty,hrg;
                qty = Long.parseLong(xjml.getText());
                hrg = Long.parseLong(xharga_jual.getText());
                sumtotal = (hrg*qty);
                model.addRow(new Object[]{xkode_barang.getText(),xnama_barang.getText(),xharga_jual.getText(),
                    xjml.getText(),sumtotal,txt_idadmin.getText()});
                jTable1.setModel(model);
                xkode_barang.requestFocus();
                xkode_barang.setText("");
                xnama_barang.setText("");
                txt_stok.setText("");
                xharga_jual.setText("");
                xjml.setText("");
                xjml_harga.setText("");
                txt_idadmin.setText("");
                totalharga();
            }else if (n ==JOptionPane.NO_OPTION) {
                xkode_barang.setText("");
                xnama_barang.setText("");
                txt_stok.setText("");
                xharga_jual.setText("");
                xjml.setText("");
                xjml_harga.setText("");
                txt_tanggal.setText("");
                txt_idadmin.setText("");
                xkode_barang.requestFocus();
            }else {
                xbayar.requestFocus();
            }
        }catch (Exception e) {
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void jbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton1ActionPerformed
       int row = jTable1.getSelectedRow();
       if(row>=0) {
        int ok=JOptionPane.showConfirmDialog(null, "Yakin Mau Hapus?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(ok==0) {
            model.removeRow(row);
            totalharga();
            xkode_barang.requestFocus();
        }
    }else{
           JOptionPane.showMessageDialog(this,
                   "Tidak ada data yang dipilih",
                   "Peringatan",
                   JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_jbutton1ActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        Connection Koneksi = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/kasircafe", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }

        String file = "E:\\Tugas_Akhir\\kasirdone\\src\\Report Transaksi.jrxml";
        JasperReport jr ;
        try {
            jr = JasperCompileManager.compileReport(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, Koneksi);
            JasperViewer.viewReport(jp);
        } catch (JRException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex );
        }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void xkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xkembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xkembaliActionPerformed

    private void xjml_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xjml_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xjml_hargaActionPerformed

    private void txt_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tanggalActionPerformed

    private void txt_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stokActionPerformed

    private void xbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xbayarActionPerformed
        // TODO add your handling code here:
       int a1,a2,kemb;
       a1=Integer.parseInt(xtotal.getText());
       a2=Integer.parseInt(xbayar.getText());
       kemb=a2-a1;
       xkembali.setText(String.valueOf(kemb));
       btnsimpan.requestFocus();
    }//GEN-LAST:event_xbayarActionPerformed

    private void xtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xtotalActionPerformed

    private void xnama_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xnama_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xnama_barangActionPerformed

    private void xharga_jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xharga_jualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xharga_jualActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        sumtotal=0;
        int row=jTable1.getRowCount();
        try {
            ResultSet rs=database.AmbilData("select * from tbl_transaksi where no_transaksi='"+xno_transaksi.getText()+"'");
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "No transaksi sudah terdaftar");
            }else{
                int total,bayar;
                total=Integer.parseInt(xtotal.getText());
                bayar=Integer.parseInt(xbayar.getText());
                if( bayar >= total) {
                    for(int i=0; i < row; i++){
                        database.eksekusi("insert into tbl_detail (no_transaksi,kd_barang,nma_barang,subtotal,total_bayar,tgl_transaksi,id_admin)values"+
                                "('"+xno_transaksi.getText()+"','"+jTable1.getValueAt(i,0) +"','"+jTable1.getValueAt(i,1) +"','"+jTable1.getValueAt(i,2) +"','"+jTable1.getValueAt(i,4) +"','"+txt_tanggal.getText()+"','"+jTable1.getValueAt(i,5) +"')");
                        database.eksekusi("update tbl_barang stok=stok-"+jTable1.getValueAt(i,3)+"','"
                                + "where kd_barang="+"'"+jTable1.getValueAt(i,0) +"");
                        
                        database.eksekusi("insert into tbl_transaksi (no_transaksi,kd_barang,jmlh_barang,id_admin,tgl_transaksi) values ('"+xno_transaksi.getText()+"',"
                                + "','"+jTable1.getValueAt(i,0) +"','"+jTable1.getValueAt(i,3) +"','"+jTable1.getValueAt(i,5) +"','"+txt_tanggal.getText()+"')");
                        JOptionPane.showMessageDialog(null, "Data telah tersimpan");
                    model.setRowCount(0);
                    buatnomer();
                    xtotal.setText("");
                    xbayar.setText("");
                    xkembali.setText("");
                    xkode_barang.requestFocus();}
                }else{
                    JOptionPane.showMessageDialog(null, "Maaf,\nJumlah Bayar Kurang!");
                    xbayar.requestFocus();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        buatnomer();
        xkode_barang.setText("");
        xnama_barang.setText("");
        txt_stok.setText("");
        xtotal.setText("");
        xharga_jual.setText("");
        xkembali.setText("");
        xbayar.setText("");
        model.setRowCount(0);
        xkode_barang.requestFocus();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Data_Transaksi().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Data_Transaksi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbutton1;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField txt_idadmin;
    private javax.swing.JTextField txt_stok;
    private javax.swing.JTextField txt_tanggal;
    private javax.swing.JTextField xbayar;
    private javax.swing.JTextField xharga_jual;
    private javax.swing.JTextField xjml;
    private javax.swing.JTextField xjml_harga;
    private javax.swing.JTextField xkembali;
    private javax.swing.JTextField xkode_barang;
    private javax.swing.JTextField xnama_barang;
    private javax.swing.JTextField xno_transaksi;
    private javax.swing.JPanel xstock;
    private javax.swing.JTextField xtotal;
    // End of variables declaration//GEN-END:variables
}